### ISSUE TITLE
Current commit fails to build, claims to need WINE

### ISSUE THREAD

**Issue by adammpkins** [yessGlory17/programmer-browser#38]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch]
- [x] Using latest version of devtools. [Check the docs for how to update]
- [x] Tried solutions mentioned in [#400]
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
ran npm run package --linux

Application should build.

## Current Behavior

npm run package --linux                                                                                19:38   07.06.22   

> package
> ts-node ./.erb/scripts/clean.js dist && npm run build && electron-builder build --publish always --win --linux

> build
> concurrently "npm run build:main" "npm run build:renderer"

[1] 
[1] > build:renderer
[1] > cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.prod.ts
[1] 
[0] 
[0] > build:main
[0] > cross-env NODE_ENV=production TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.main.prod.ts
[0] 
[0] npm run build:main exited with code 0
[1] npm run build:renderer exited with code 0
  • electron-builder  version=23.0.3 os=5.13.0-44-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/build/builder-effective-config.yaml
  • installing production dependencies  platform=linux arch=x64 appDir=/home/adammpkins/programmer-browser/release/app
  • packaging       platform=linux arch=x64 electron=18.3.0 appOutDir=release/build/linux-unpacked
  • building        target=AppImage arch=x64 file=release/build/ProgrammerBrowser-0.1.8.AppImage
  • installing production dependencies  platform=win32 arch=x64 appDir=/home/adammpkins/programmer-browser/release/app
  • packaging       platform=win32 arch=x64 electron=18.3.0 appOutDir=release/build/win-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v18.3.0/electron-v18.3.0-win32-x64.zip size=89 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v18.3.0/electron-v18.3.0-win32-x64.zip duration=2.457s
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=737ms
  ⨯ wine is required, please see https://electron.build/multi-platform-build#linux  
  ⨯ /home/adammpkins/programmer-browser/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: /home/adammpkins/programmer-browser/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/home/adammpkins/programmer-browser/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:472:26)
    at ChildProcess.emit (node:events:365:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
From previous event:
    at processImmediate (node:internal/timers:464:21)
From previous event:
    at WinPackager.signApp (/home/adammpkins/programmer-browser/node_modules/app-builder-lib/src/winPackager.ts:376:27)
    at WinPackager.doSignAfterPack (/home/adammpkins/programmer-browser/node_modules/app-builder-lib/src/platformPackager.ts:329:16)
    at WinPackager.doPack (/home/adammpkins/programmer-browser/node_modules/app-builder-lib/src/platformPackager.ts:314:7)
    at WinPackager.pack (/home/adammpkins/programmer-browser/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/home/adammpkins/programmer-browser/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/home/adammpkins/programmer-browser/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/adammpkins/programmer-browser/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/adammpkins/programmer-browser/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/adammpkins/programmer-browser/node_modules/builder-util/src/promise.ts:12:14)

## Steps to Reproduce

1.Pull the latest commit.

2. Run npm run package --linux

3.Exceptions

4.

## Your Environment

- Node version : 16.2.0
- Operating System and version : Ubuntu 20.04

**Comment by yessGlory17** [comment]
try this

```js
npm run package:linux
```

**Comment by adammpkins** [comment]
Your suggestion worked. This should be updated in the docs.

**Comment by yessGlory17** [comment]
:+1:
